pipeline {
    agent any

    parameters {
        choice(
            name: 'MAVEN_VERSION',
            choices: ['M3'],
            description: 'Select Maven version for the build'
        )
        choice(
            name: 'ENVIRONMENT',
            choices: ['DEV', 'UAT', 'PROD'],
            description: 'Select environment for deployment'
        )
        string(
            name: 'DEPLOYMENT_NAME',
            defaultValue: 'defaultDeployment',
            description: 'Deployment Name'
        )
        string(
            name: 'VERSION',
            defaultValue: '0.0.0',
            description: 'Version of the application'
        )
    }

    tools {
        maven 'M3' // Esto solo asegura que haya al menos una versión cargada.
    }

    stages {
        stage("Clean Up") {
            steps {
                echo "Cleaning up workspace..."
                deleteDir()
            }
        }

        stage("Clone Repo") {
            steps {
                echo "Cloning Repository..."
                git 'https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }

        stage("Build") {
            steps {
                script {
                    def mvnHome = tool name: "${params.MAVEN_VERSION}", type: 'maven'
                    env.PATH = "${mvnHome}/bin:${env.PATH}"
                }
                echo "Building the project with Maven ${params.MAVEN_VERSION}..."
                dir('simple-java-maven-app') {
                    sh "mvn clean install"
                }
            }
        }

        stage("Test") {
            steps {
                dir('simple-java-maven-app') {
                    sh "mvn test"
                }
            }
        }

        stage("Confirm Deployment (For PROD Only)") {
            when {
                expression { return params.ENVIRONMENT == 'PROD' }
            }
            steps {
                script {
                    def userChoice = input(
                        message: "You are about to deploy to ${params.ENVIRONMENT} the '${params.VERSION}' version. Select Yes/No to continue:",
                        parameters: [
                            choice(
                                name: 'Confirmation',
                                choices: ['Yes', 'No'],
                                description: 'Do you want to proceed with the deployment?'
                            )
                        ]
                    )

                    if (userChoice != 'Yes') {
                        error("Deployment to ${params.ENVIRONMENT} - ${params.VERSION} was cancelled by the user.")
                    }
                }
            }
        }

        stage("Deployment") {
            steps {
                echo "Proceeding with deployment ${params.DEPLOYMENT_NAME} - Version: ${params.VERSION} to ${params.ENVIRONMENT} environment..."
                // Tu lógica de despliegue real iría aquí
            }
        }
    }
}
